apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: ashupod1
spec:
  containers:
  - command:
    - ping
    - fb.com
    image: busybox
    name: ashupod1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never # this change 
status: {}

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    delvex: ashup11
  name: ashupod2
spec:
  containers:
  - image: nginx
    name: ashupod2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# creating serivce for pod 2 

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashusvc2
  name: ashusvc2
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    delvex: ashup11 # label of pod2 
  type: ClusterIP
status:
  loadBalancer: {}